import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import dayjs from "dayjs";

import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

import { api, RouterOutputs } from "~/utils/api";
import Image from "next/image";
import { LoadingPage } from "~/components/Loading";
import { useState } from "react";

const CreatePostWizard = () => {
  const { user } = useUser();

  const [input, setInput] = useState("");

  const ctx = api.useContext()
  const {mutate, isLoading: isPosting} = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate()
    }
  });

  if (!user) return null;


  return (<div className="flex gap-3 w-full">
    <Image
      width={56} height={56} src={user.profileImageUrl} alt="Profile Image" className="w-14 h-14 rounded-full" />

    <input placeholder="Type some emojis" className="bg-transparent grow outline-none" 
    value={input}
    onChange={(e) => setInput(e.target.value)}
    disabled={isPosting}
    />
    <button onClick={() => mutate({content: input})}>Post</button>
  </div>)
}


type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className=" border-b border-slate-400 flex p-4 gap-3   " key={post.id}>
      <Image src={author.profilePicture} alt="Profile Image" width={56} height={56} className="w-14 h-14 rounded-full " />
      <div className="flex flex-col text-slate-200">
        <div><span>{`@${author.username}`}</span> · <span>{`${dayjs(post.createdAt).fromNow()}`}</span></div>
        <span className="text-xl">{post.content}</span>
      </div>

    </div>
  )
}
const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading)
    return (
      <div className="flex grow">
        <LoadingPage />
      </div>
    );

  if (!data) return <div>Something went wrong</div>;

  return (
    <div className="flex grow flex-col overflow-y-scroll">
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};
const Home: NextPage = () => {

const {isLoaded: userLoaded, isSignedIn} = useUser()
  api.posts.getAll.useQuery();

  

  if (!userLoaded) return <div />;

  
 


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className=" h-full w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4 ">
            {!isSignedIn && <SignInButton />}{isSignedIn && <CreatePostWizard />}

          </div>
          <Feed />
        </div>


      </main>
    </>
  );
};

export default Home;
